### ISSUE TITLE
Gem Install

### ISSUE THREAD

**Issue by noahc** [taf2/rb-brill-tagger#1]
I get the following issue when I try to install this. Can you tell me if this is related to your gem or my local system?[

~]$ sudo gem install rbtagger
Fetching: rbtagger-0.4.7.gem (100%)
Building native extensions.  This could take a while...
Successfully installed rbtagger-0.4.7
1 gem installed
Installing ri documentation for rbtagger-0.4.7...

RDoc::Parser::Ruby failure around line 72841 of
lib/brill/brown/Lexicon.rb

Before reporting this, could you check that the file you're documenting
has proper syntax:

  /usr/local/bin/ruby -c lib/brill/brown/Lexicon.rb

RDoc is not a full Ruby parser and will fail when fed invalid ruby programs.

The internal error was:

```
(RDoc::RubyLex::Error) unknown type of %string "C"
```

ERROR:  While generating documentation for rbtagger-0.4.7
... MESSAGE:   unknown type of %string "C"
... RDOC args: --ri --op /usr/local/lib/ruby/gems/1.9.1/doc/rbtagger-0.4.7/ri --main README lib ext LICENSE README --title rbtagger-0.4.7 Documentation --quiet

**Comment by taf2** [comment]
hrm... something must have changed in rdoc... if i'm right the gem is installed fine, but rdocs for it won't be...
